name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install FontAwesome
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-font-awesome

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex 
        latexmk_use_xelatex: true 

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-resume
        path: resume.pdf

    - name: Commit & Push the PDF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add resume.pdf
        git commit -m "Auto-update PDF from LaTeX"
        git push
