name: Compile LaTeX to PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: ./main.pdf
